In [1]:
import pandas as pd
import os
import numpy as np

## Part 1

In [2]:
courses_file_path = os.path.join('..', 'data', 'raw', 'courses.csv')
enrollment_file_path = os.path.join('..', 'data', 'raw', 'enrollments.csv')
students_file_path = os.path.join('..', 'data', 'raw', 'students.csv')

courses_df = pd.read_csv(courses_file_path)
enrollment_df = pd.read_csv(enrollment_file_path)
students_df = pd.read_csv(students_file_path)

In [3]:
courses_df.shape

(8, 7)

In [4]:
enrollment_df.shape

(59, 9)

In [5]:
students_df.shape

(30, 11)

In [6]:
print(courses_df.columns, "\n", courses_df.dtypes)

Index(['course_id', 'department', 'course_number', 'course_title', 'credits',
       'level', 'delivery'],
      dtype='str')
 course_id          str
department         str
course_number    int64
course_title       str
credits          int64
level              str
delivery           str
dtype: object

In [7]:
print(enrollment_df.columns, "\n", enrollment_df.dtypes)

Index(['enrollment_id', 'student_id', 'course_id', 'term', 'status',
       'midterm_score', 'final_score', 'project_score', 'attendance_pct'],
      dtype='str')
 enrollment_id         str
student_id            str
course_id             str
term                  str
status                str
midterm_score       int64
final_score       float64
project_score     float64
attendance_pct    float64
dtype: object

In [8]:
print(students_df.columns, "\n", students_df.dtypes)

Index(['student_id', 'first_name', 'last_name', 'program', 'year', 'age',
       'active', 'entry_term', 'gpa', 'credits_completed', 'advisor'],
      dtype='str')
 student_id               str
first_name               str
last_name                str
program                  str
year                     str
age                  float64
active                   str
entry_term               str
gpa                  float64
credits_completed      int64
advisor                  str
dtype: object

In [9]:
courses_nas = courses_df.isna().sum().sum()
enrollment_nas = enrollment_df.isna().sum().sum()
students_nas = students_df.isna().sum().sum()

print(f"{courses_nas} NAs in Courses dataframe")
print(f"{enrollment_nas} NAs in Enrollment dataframe")
print(f"{students_nas} NAs in Students dataframe")

0 NAs in Courses dataframe
10 NAs in Enrollment dataframe
6 NAs in Students dataframe

In [10]:
courses_nas = courses_df.isna().sum().sum()
enrollment_nas = enrollment_df.isna().sum().sum()
students_nas = students_df.isna().sum().sum()

print("NAs in Courses Dataframe:", courses_nas)
print("NAs in Enrollment Dataframe:", enrollment_nas)
print("NAs in Student Dataframe:", students_nas)

NAs in Courses Dataframe: 0
NAs in Enrollment Dataframe: 10
NAs in Student Dataframe: 6

The likely key columns for the course, enrollment, and student dataframes are: course_id, enrollment_id, and student_id, respectively.

The largest concern with data-quality is the presence of NA values in Enrollment and Students. These values will either need to filled with some default or removed from the tables.

## Part 2

Using the student-level table:

1. select a meaningful subset using at least two conditions;

2. create one derived variable;

3. use .loc[] correctly;

4. demonstrate one list or dictionary comprehension related to the data.

In [11]:
upperclassmen_high_gpa = (students_df['year'].isin(['3rd','4th']) & (students_df['gpa']>=3.5))

students_df.loc[upperclassmen_high_gpa]

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno
14,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36,Dr. Shah
17,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36,Dr. Kim
24,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84,Dr. Moreno

In [12]:
students_df['award_candidate'] = 'No'

students_df.loc[upperclassmen_high_gpa, 'award_candidate'] = 'Yes'

students_df.head(6)

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,award_candidate
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,No
1,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah,No
2,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,Dr. Reed,No
3,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63,Dr. Kim,No
4,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18,Dr. Kim,No
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno,Yes

In [13]:
award_candidates = [students_df.iloc[i, 0] for i in range(len(students_df)) if students_df.iloc[i, -1] == 'Yes']

print(award_candidates)

['S1006', 'S1015', 'S1018', 'S1025']

I chose to select the upperclassmen with good gpas. I did so by filtering students in their 3rd or 4th year and selected those with a gpa of 3.0 or higher. This lets me see who the top performing upperclassmen are and who may be eligable for scholarships or awards. I then used this condition to derive a new variable, award_candidate, that indicates whether or not a student is eligable for an award. After creating this derived variable, I used list comprehension to find the student ids of students who are eligable for awards.

## Part 3

In [14]:
display(enrollment_df.head(3))
display(students_df.head(3))
display(courses_df.head(3))

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct
0,E5001,S1001,C102,Spring 2026,Completed,96,65.0,65.0,94.7
1,E5002,S1001,C106,Spring 2026,Completed,81,80.0,63.0,96.6
2,E5003,S1001,C103,Spring 2026,Completed,77,67.0,72.0,88.6

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,award_candidate
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,No
1,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah,No
2,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,Dr. Reed,No

,course_id,department,course_number,course_title,credits,level,delivery
0,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person
1,C102,STA,270,Applied Statistics,3,Undergraduate,Hybrid
2,C103,CS,126,Introduction to Computing,4,Undergraduate,In Person

In [15]:
students_enrollment = students_df.merge(enrollment_df, on='student_id', how='left', validate='one_to_many', indicator=True)
students_enrollment.loc[~(students_enrollment['_merge']=='both'), ['_merge']]

       _merge
58  left_only

After merging students with enrollment, only one entry was found to not exist in both.

In [16]:
students_enrollment_courses = courses_df.merge(students_enrollment, on='course_id', how='left', validate='one_to_many')
students_enrollment_courses.head(5)

,course_id,department,course_number,course_title,credits,level,delivery,student_id,first_name,last_name,...,advisor,award_candidate,enrollment_id,term,status,midterm_score,final_score,project_score,attendance_pct,_merge
0,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1002,Maya,Patel,...,Dr. Shah,No,E5005,Fall 2025,Completed,90.0,55.0,79.0,85.8,both
1,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1004,Sofia,Johnson,...,Dr. Kim,No,E5008,Fall 2025,Completed,87.0,58.0,NaN,75.6,both
2,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1005,Ethan,Kim,...,Dr. Kim,No,E5010,Spring 2026,Completed,73.0,57.0,99.0,82.9,both
3,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1006,Liam,Martinez,...,Dr. Moreno,Yes,E5013,Fall 2026,Enrolled,98.0,81.0,82.0,80.0,both
4,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1008,Lucas,Wilson,...,Dr. Shah,No,E5018,Spring 2026,Completed,74.0,70.0,62.0,87.4,both

When merging students with enrollment, the student entries get duplicated since it is a one to many relationship where students is the one and enrollment is the many. After merging students with enrollment, the resulting dataframe is merged with coourses in a one to many relationship where courses is the one and the student-enrollment dataframe is the many. Because courses is the one, the entries in courses get duplicated in order to merge with the many in student-enrollment.

## Part 4

In [17]:
students_enrollment_courses.isna().sum()

course_id            0
department           0
course_number        0
course_title         0
credits              0
level                0
delivery             0
student_id           0
first_name           0
last_name            0
program              0
year                 0
age                  4
active               0
entry_term           0
gpa                  4
credits_completed    0
advisor              1
award_candidate      0
enrollment_id        0
term                 0
status               0
midterm_score        0
final_score          5
project_score        3
attendance_pct       2
_merge               0
dtype: int64

In [18]:
students_enrollment_courses.isna().mean() * 100

course_id            0.000000
department           0.000000
course_number        0.000000
course_title         0.000000
credits              0.000000
level                0.000000
delivery             0.000000
student_id           0.000000
first_name           0.000000
last_name            0.000000
program              0.000000
year                 0.000000
age                  7.017544
active               0.000000
entry_term           0.000000
gpa                  7.017544
credits_completed    0.000000
advisor              1.754386
award_candidate      0.000000
enrollment_id        0.000000
term                 0.000000
status               0.000000
midterm_score        0.000000
final_score          8.771930
project_score        5.263158
attendance_pct       3.508772
_merge               0.000000
dtype: float64

In [19]:
na_rows = students_enrollment_courses.loc[students_enrollment_courses.isna().any(axis=1)]

na_rows

,course_id,department,course_number,course_title,credits,level,delivery,student_id,first_name,last_name,...,advisor,award_candidate,enrollment_id,term,status,midterm_score,final_score,project_score,attendance_pct,_merge
1,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1004,Sofia,Johnson,...,Dr. Kim,No,E5008,Fall 2025,Completed,87.0,58.0,NaN,75.6,both
2,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1005,Ethan,Kim,...,Dr. Kim,No,E5010,Spring 2026,Completed,73.0,57.0,99.0,82.9,both
5,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,S1014,Henry,Anderson,...,Dr. Shah,No,E5028,Fall 2025,Completed,88.0,NaN,77.0,77.6,both
11,C102,STA,270,Applied Statistics,3,Undergraduate,Hybrid,S1008,Lucas,Wilson,...,Dr. Shah,No,E5017,Fall 2025,Completed,89.0,65.0,79.0,NaN,both
17,C102,STA,270,Applied Statistics,3,Undergraduate,Hybrid,S1022,Julian,Wright,...,Dr. Shah,No,E5045,Spring 2026,Completed,62.0,61.0,71.0,85.2,both
27,C104,MAT,239,Linear Algebra,3,Undergraduate,In Person,S1013,Amara,Taylor,...,Dr. Kim,No,E5026,Fall 2026,Enrolled,68.0,78.0,77.0,81.7,both
29,C104,MAT,239,Linear Algebra,3,Undergraduate,In Person,S1026,Isaac,Adams,...,NaN,No,E5052,Fall 2026,Enrolled,70.0,63.0,68.0,90.7,both
30,C104,MAT,239,Linear Algebra,3,Undergraduate,In Person,S1029,Aria,Campbell,...,Dr. Moreno,No,E5056,Spring 2026,Completed,88.0,57.0,85.0,80.3,both
32,C105,STA,444,Statistical Computing,3,Undergraduate,Online,S1006,Liam,Martinez,...,Dr. Moreno,Yes,E5012,Fall 2026,Enrolled,75.0,NaN,68.0,97.2,both
34,C105,STA,444,Statistical Computing,3,Undergraduate,Online,S1018,Samuel,Hall,...,Dr. Kim,Yes,E5037,Spring 2026,Completed,58.0,NaN,65.0,95.9,both
37,C106,STA,556,Statistics and Data Science Computing Workflows,3,Graduate,In Person,S1002,Maya,Patel,...,Dr. Shah,No,E5004,Fall 2025,Completed,86.0,NaN,85.0,77.3,both
43,C107,CS,345,Databases,3,Undergraduate,Online,S1017,Nora,Lewis,...,Dr. Moreno,No,E5034,Spring 2026,Completed,61.0,70.0,86.0,NaN,both
45,C107,CS,345,Databases,3,Undergraduate,Online,S1021,Layla,King,...,Dr. Shah,No,E5042,Fall 2025,Completed,89.0,68.0,NaN,73.9,both
46,C107,CS,345,Databases,3,Undergraduate,Online,S1022,Julian,Wright,...,Dr. Shah,No,E5044,Fall 2025,Completed,76.0,74.0,72.0,92.6,both
49,C108,MAT,442,Probability,3,Undergraduate,Hybrid,S1005,Ethan,Kim,...,Dr. Kim,No,E5011,Fall 2025,Completed,68.0,55.0,82.0,91.0,both
50,C108,MAT,442,Probability,3,Undergraduate,Hybrid,S1009,Emma,Chen,...,Dr. Moreno,No,E5020,Spring 2026,Completed,73.0,NaN,71.0,84.2,both
54,C108,MAT,442,Probability,3,Undergraduate,Hybrid,S1013,Amara,Taylor,...,Dr. Kim,No,E5025,Fall 2025,Completed,83.0,70.0,NaN,91.2,both
56,C108,MAT,442,Probability,3,Undergraduate,Hybrid,S1029,Aria,Campbell,...,Dr. Moreno,No,E5057,Fall 2026,Enrolled,73.0,62.0,78.0,94.2,both

In [22]:
course_gpas = students_enrollment_courses.pivot_table(
    index='course_id',
    columns='level',
    values='gpa',
    aggfunc='mean'
)

course_gpas = course_gpas.merge(courses_df[['course_id', 'course_title', 'course_number']], 
                                        how='left', on='course_id', validate='one_to_one')

display(course_gpas)

path = os.path.join("..", 'data', 'processed', 'avg_course_gpa.csv')
course_gpas.to_csv(path)

,course_id,Graduate,Undergraduate,course_title,course_number
0,C101,NaN,3.2125,Exploratory Data Analysis,141
1,C102,NaN,3.0740,Applied Statistics,270
2,C103,NaN,3.4760,Introduction to Computing,126
3,C104,NaN,2.9800,Linear Algebra,239
4,C105,NaN,3.6240,Statistical Computing,444
5,C106,3.335714,NaN,Statistics and Data Science Computing Workflows,556
6,C107,NaN,3.5800,Databases,345
7,C108,NaN,3.0700,Probability,442

I decided to reshape the data by pivotting. I used pivot_table to find the mean gpa for every course, by level, in course_id. I then merged the resulting wide datframe with the courses dataframe to add back important information like the course title and course number.

Replacing every NA value with zeros is a bad idea for a few reasons. If you replace every NA value with zero then when you want to do some kind of computation, like finding the mean, the zero values will influence whatever value you are deriving. Another reason, is that a zero may not be representative of the data. For example, after my pivot I was left with NA mean gpa values. If I replaced these mean gpa values with zeros then somebody reading the table may be confused and think the average gpa for the course is zero when really there is no mean gpa because the course is not offered at that level. Filling all NAs with zeros might also be bad if you have columns with conflicting data types, like a str column.