In [2]:
import pandas as pd
import numpy as np

## Part 1

In [3]:
participants = pd.DataFrame({
    "id": [101, 102, 103, 104, 105, 106],
    "age": [24, 31, 27, 19, 42, 35],
    "group": ["A", "B", "A", "B", "A", "B"]
})

In [4]:
scores = pd.DataFrame({
    "id": [101, 102, 103, 105, 106, 107],
    "score": [81, 94, 88, 91, 85, 79]
})

In [5]:
display(participants)
display(scores)

    id  age group
0  101   24     A
1  102   31     B
2  103   27     A
3  104   19     B
4  105   42     A
5  106   35     B

    id  score
0  101     81
1  102     94
2  103     88
3  105     91
4  106     85
5  107     79

## Part 2 Inner Join

In [6]:
inner = participants.merge(
    scores,
    on="id",
    how="inner"
)

In [7]:
display(inner)
inner.shape

    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88
3  105   42     A     91
4  106   35     B     85

(5, 4)

Questions

Which IDs were removed?

104 and 107

Why?

Because an inner join joins the dataframe on the intersection of the specified column of both dataframes.

Did the number of rows match your prediction?

Yes

## Part 3

In [8]:
left = participants.merge(
    scores,
    on="id",
    how="left"
)

left

    id  age group  score
0  101   24     A   81.0
1  102   31     B   94.0
2  103   27     A   88.0
3  104   19     B    NaN
4  105   42     A   91.0
5  106   35     B   85.0

Questions

Which table defines the resulting population?
The "left" table. The dataframe that using the .merge() method.

What happened to ID 104?

Because 104 does not exist in scores it is assigned an NA value.

Why is its score missing?

Because it is not defined in the scores dataframe.

## Part 4 — Outer join

In [9]:
outer = participants.merge(
    scores,
    on="id",
    how="outer"
)
outer

    id   age group  score
0  101  24.0     A   81.0
1  102  31.0     B   94.0
2  103  27.0     A   88.0
3  104  19.0     B    NaN
4  105  42.0     A   91.0
5  106  35.0     B   85.0
6  107   NaN   NaN   79.0

It will find the union of the two datasets

In [11]:
right = participants.merge(
    scores,
    on="id",
    how="right"
)

right

    id   age group  score
0  101  24.0     A     81
1  102  31.0     B     94
2  103  27.0     A     88
3  105  42.0     A     91
4  106  35.0     B     85
5  107   NaN   NaN     79

## Part 5 — Diagnose joins with indicator=True

In [12]:
diagnostic = participants.merge(
    scores,
    on="id",
    how="outer",
    indicator=True
)

diagnostic

    id   age group  score      _merge
0  101  24.0     A   81.0        both
1  102  31.0     B   94.0        both
2  103  27.0     A   88.0        both
3  104  19.0     B    NaN   left_only
4  105  42.0     A   91.0        both
5  106  35.0     B   85.0        both
6  107   NaN   NaN   79.0  right_only

In [13]:
diagnostic["_merge"].value_counts()

_merge
both          5
left_only     1
right_only    1
Name: count, dtype: int64

Questions

How many rows matched?

5

How many occurred only in the participant table?

1

How many occurred only in the score table?

1

Challenge

Extract only unmatched records.