In [1]:
import pandas as pd

### Part 1

In [2]:
data = {
    "id": [101, 102, 103, 104, 105, 106],
    "age": [24, 31, 27, 19, 42, 35],
    "group": ["A", "B", "A", "B", "A", "B"],
    "score": [81, 94, 88, 72, 91, 85]
}

df = pd.DataFrame(data)

In [3]:
display(df)

    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88
3  104   19     B     72
4  105   42     A     91
5  106   35     B     85

In [4]:
df.head()
df.shape
df.columns
df.index
df.dtypes
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      6 non-null      int64
 1   age     6 non-null      int64
 2   group   6 non-null      str
 3   score   6 non-null      int64
dtypes: int64(3), str(1)
memory usage: 324.0 bytes

               id        age      score
count    6.000000   6.000000   6.000000
mean   103.500000  29.666667  85.166667
std      1.870829   8.189424   7.884584
min    101.000000  19.000000  72.000000
25%    102.250000  24.750000  82.000000
50%    103.500000  29.000000  86.500000
75%    104.750000  34.000000  90.250000
max    106.000000  42.000000  94.000000

How many observations are there?
6

How many variables?
3

Which columns are numeric?
id, age, score

What is the default index?
0 to number of observations

What does df.shape return?
It returns the number of rows and columns.

### Part 2

In [5]:
df.head(6)

    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88
3  104   19     B     72
4  105   42     A     91
5  106   35     B     85

In [6]:
age = df["age"]
type(age)

pandas.Series

In [7]:
age_df = df[["age"]]
type(age_df)

pandas.DataFrame

Explain the difference between df["age"] an df[["age"]]

df["age"] will return a pandas series and df[["age"]] will return a dataframe with only the age column.

### Part 3

In [8]:
df["score"]

0    81
1    94
2    88
3    72
4    91
5    85
Name: score, dtype: int64

In [9]:
df[["age", "score"]]

   age  score
0   24     81
1   31     94
2   27     88
3   19     72
4   42     91
5   35     85

Create analysis_df containing only:

id

group

score

In [10]:
df[['id', 'group', 'score']]

    id group  score
0  101     A     81
1  102     B     94
2  103     A     88
3  104     B     72
4  105     A     91
5  106     B     85

### Part 4

In [11]:
df.iloc[0]

id       101
age       24
group      A
score     81
Name: 0, dtype: object

In [12]:
df.iloc[0:3]

    id  age group  score
0  101   24     A     81
1  102   31     B     94
2  103   27     A     88

In [13]:
df.iloc[1:4, 1:3]

   age group
1   31     B
2   27     A
3   19     B

In [14]:
df.iloc[[0, 2, 5]]

    id  age group  score
0  101   24     A     81
2  103   27     A     88
5  106   35     B     85

What does the first argument to .iloc[] control?

    It locates elements of a dataframe by row index.

What does the second argument control?

    It locates elements of dataframe by column index.

Is the stop value included in positional slicing?

    No

### Part 5

In [15]:
df = df.set_index("id")

In [16]:
display(df)
df.index

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
104   19     B     72
105   42     A     91
106   35     B     85

RangeIndex(start=101, stop=107, step=1, name='id')

In [17]:
df.loc[101]

age      24
group     A
score    81
Name: 101, dtype: object

In [18]:
df.iloc[0]

age      24
group     A
score    81
Name: 101, dtype: object

They identify the same observation here. Why do the two commands mean different things?

df.loc[] locates elements by the value, df.iloc locates elements by index similar to a list.

### Part 6

In [19]:
df.loc[101]

age      24
group     A
score    81
Name: 101, dtype: object

In [20]:
df.loc[[101, 103, 105]]

     age group  score
id
101   24     A     81
103   27     A     88
105   42     A     91

In [21]:
df.loc[
    [101, 103],
    ["age", "score"]
]

     age  score
id
101   24     81
103   27     88

Select IDs 102, 104, and 106 and display only:

    age
    group
    score

In [22]:
df.loc[[102, 104, 106], ['age', 'group', 'score']]

     age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85

### Part 7

In [23]:
small = pd.DataFrame(
    {"value": [10, 20, 30, 40]},
    index=[101, 205, 310, 412]
)

In [24]:
small.loc[205]

value    20
Name: 205, dtype: int64

In [25]:
small.iloc[1]

value    20
Name: 205, dtype: int64

.loc  uses the value
.iloc uses index

### Part 8

In [26]:
df.iloc[1:4]

     age group  score
id
102   31     B     94
103   27     A     88
104   19     B     72

In [27]:
df.loc[102:105]

     age group  score
id
102   31     B     94
103   27     A     88
104   19     B     72
105   42     A     91

Why does label-based slicing behave differently from positional slicing?

Label-based slicing is inclusive and positional slicing is exclusive.

### Part 9

In [28]:
df.loc[:, ["age", "score"]]

     age  score
id
101   24     81
102   31     94
103   27     88
104   19     72
105   42     91
106   35     85

In [29]:
df.loc[
    102:105,
    ["age", "score"]
]

     age  score
id
102   31     94
103   27     88
104   19     72
105   42     91

Select IDs 101 through 104 and show only group and score.

In [30]:
df.loc[101:104, ['group', 'score']]

    group  score
id
101     A     81
102     B     94
103     A     88
104     B     72

### Part 10

In [31]:
condition = df["score"] > 80

In [32]:
display(condition)
type(condition)

id
101     True
102     True
103     True
104    False
105     True
106     True
Name: score, dtype: bool

pandas.Series

In [33]:
df.loc[condition]

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

What does each True and False represent?

Represents the rows where the condition is satisfied.

### Part 11

In [34]:
df.loc[df["score"] > 80]

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

In [35]:
df.loc[df["age"] >= 30]

     age group  score
id
102   31     B     94
105   42     A     91
106   35     B     85

In [36]:
df.loc[df["group"] == "A"]

     age group  score
id
101   24     A     81
103   27     A     88
105   42     A     91

Create separate subsets for participants who are:

    younger than 30;

    in group B;

    scoring at least 85.

In [37]:
df.loc[df['age'] < 30]

     age group  score
id
101   24     A     81
103   27     A     88
104   19     B     72

In [38]:
df.loc[df['group']=='B']

     age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85

In [39]:
df.loc[df['score']>=30]

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
104   19     B     72
105   42     A     91
106   35     B     85

### Part 12

In [40]:
df.loc[
    (df["age"] < 30) &
    (df["score"] > 80)
]

     age group  score
id
101   24     A     81
103   27     A     88

In [41]:
df.loc[
    (df["group"] == "A") |
    (df["score"] > 90)
]

     age group  score
id
101   24     A     81
102   31     B     94
103   27     A     88
105   42     A     91

In [42]:
df.loc[
    ~(df["group"] == "A")
]

     age group  score
id
102   31     B     94
104   19     B     72
106   35     B     85

Find participants who are at least 30 years old and score at least 85.

In [43]:
df.loc[(df['age']>=30)&(df['score']>=85)]

     age group  score
id
102   31     B     94
105   42     A     91
106   35     B     85

### Part 13

Without executing the code, predict which IDs will appear:

In [44]:
df.loc[
    (df["group"] == "A") &
    (df["score"] >= 90)
]

     age group  score
id
105   42     A     91

It will create a subset where group is A and score is at least 90

Did your result match your prediction?

Yes

### Part 14

In [45]:
df.loc[
    df["score"] >= 85,
    ["age", "group", "score"]
]

     age group  score
id
102   31     B     94
103   27     A     88
105   42     A     91
106   35     B     85

Return only group and score for participants aged at least 30.

In [46]:
df.loc[df['age']>=30, ['group', 'score']]

    group  score
id
102     B     94
105     A     91
106     B     85

### Part 15

In [47]:
df2 = pd.DataFrame(
    {
        "id": range(201, 209),
        "group": ["A", "B", "C", "A", "C", "B", "A", "C"],
        "score": [81, 94, 88, 72, 91, 85, 79, 96]
    }
).set_index("id")

In [48]:
df2.loc[
    df2["group"].isin(["A", "C"])
]

    group  score
id
201     A     81
203     C     88
204     A     72
205     C     91
207     A     79
208     C     96

Select observations in groups B or C and with score at least 85.

In [49]:
df2.loc[(df2['score']>=85) & (df2['group'].isin(['B','C']))]

    group  score
id
202     B     94
203     C     88
205     C     91
206     B     85
208     C     96

### Part 16

In [50]:
missing_df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "age": [21, 32, None, 45, 28],
        "score": [81, None, 77, 92, 88]
    }
).set_index("id")

In [51]:
display(missing_df)
print(missing_df.isna())
print(missing_df.isna().sum())

     age  score
id
1   21.0   81.0
2   32.0    NaN
3    NaN   77.0
4   45.0   92.0
5   28.0   88.0

      age  score
id
1   False  False
2   False   True
3    True  False
4   False  False
5   False  False
age      1
score    1
dtype: int64

In [52]:
missing_df.loc[
    missing_df["score"].isna()
]

     age  score
id
2   32.0    NaN

In [53]:
missing_df.loc[
    missing_df["score"].notna()
]

     age  score
id
1   21.0   81.0
3    NaN   77.0
4   45.0   92.0
5   28.0   88.0

Why is score = 0 different from score = missing in statistical analysis?

Because 0 is an actual value not a NULL type

### Part 17

In [54]:
df["performance"] = "medium"

In [55]:
df.loc[
    df["score"] >= 90,
    "performance"
] = "high"

In [56]:
df.loc[
    df["score"] < 80,
    "performance"
] = "low"

Create an age_group variable:

    young → age < 30
    older → age >= 30

using .loc.

In [57]:
df['age_group'] = 'young'

df.loc[df['age']<30, 'age_young'] = 'young'
df.loc[df['age']>=30, 'age_young'] = 'old'

In [58]:
df

     age group  score performance age_group age_young
id
101   24     A     81      medium     young     young
102   31     B     94        high     young       old
103   27     A     88      medium     young     young
104   19     B     72         low     young     young
105   42     A     91        high     young       old
106   35     B     85      medium     young       old

### Part 18

In [59]:
df[df["score"] > 80]["score"] = 100

/var/folders/wf/xybsd4516gbf298t3ng0mmrm0000gn/T/ipykernel_28813/2702008686.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[df["score"] > 80]["score"] = 100

In [60]:
df.loc[
    df["score"] > 80,
    "score"
] = 100

Why is the .loc version clearer? Connect your answer to Week 2’s discussion of references and mutation.

.loc[] mutates in place instead of chaining

### Part 19

Suppose the study protocol says:

    Include adults in group A who have a non-missing score.

In [61]:
analysis = df.loc[
    (df["age"] >= 18) &
    (df["group"] == "A") &
    (df["score"].notna())
]

In [62]:
analysis

     age group  score performance age_group age_young
id
101   24     A    100      medium     young     young
103   27     A    100      medium     young     young
105   42     A    100        high     young       old

### Part 20

Age criterion: >= 30

Score criterion: >= 85

Missing-data criterion: no NAs

Variables required: age and score

In [63]:
eligible = (
    (df["age"] >= 30) &
    (df["score"] >= 85) &
    (df["score"].notna())
)

analysis_df = df.loc[
    eligible,
    ["age", "group", "score"]
]

analysis_df

     age group  score
id
102   31     B    100
105   42     A    100
106   35     B    100

### Part 21

In [64]:
participants = pd.DataFrame(
    {
        "id": range(1001, 1011),
        "age": [22, 34, 29, 41, 19, 37, 26, 45, 31, 28],
        "group": ["A", "B", "A", "C", "B", "A", "C", "B", "A", "C"],
        "score": [78, 91, 85, 88, 72, 95, 81, 67, 90, 84]
    }
).set_index("id")

#### Part A

In [65]:
older = (participants['age'] >= 30)
participants.loc[older]

      age group  score
id
1002   34     B     91
1004   41     C     88
1006   37     A     95
1008   45     B     67
1009   31     A     90

#### Part B

In [66]:
groups_ac = (participants['group'].isin(['A','C']))
participants.loc[groups_ac]

      age group  score
id
1001   22     A     78
1003   29     A     85
1004   41     C     88
1006   37     A     95
1007   26     C     81
1009   31     A     90
1010   28     C     84

#### Part C

In [67]:
high_scores = (participants['score'] >= 85)
participants.loc[high_scores]

      age group  score
id
1002   34     B     91
1003   29     A     85
1004   41     C     88
1006   37     A     95
1009   31     A     90

#### Part D

In [68]:
older_higher = (older &  high_scores)
participants.loc[older_higher]

      age group  score
id
1002   34     B     91
1004   41     C     88
1006   37     A     95
1009   31     A     90

#### Part E

In [69]:
high_score_summary = participants.loc[high_scores, ['group', 'score']]
high_score_summary

     group  score
id
1002     B     91
1003     A     85
1004     C     88
1006     A     95
1009     A     90

#### Part F

In [70]:
group_a_good = ((participants['group'] == 'A') & (participants['score']>=80))
participants.loc[group_a_good]

      age group  score
id
1003   29     A     85
1006   37     A     95
1009   31     A     90

#### Part G

In [71]:
not_group_b = ~(participants['group']=='B')
participants.loc[not_group_b]

      age group  score
id
1001   22     A     78
1003   29     A     85
1004   41     C     88
1006   37     A     95
1007   26     C     81
1009   31     A     90
1010   28     C     84

### Part 22

### Part 23

In [72]:
def select_high_scores(
    data: pd.DataFrame,
    minimum_score: float
) -> pd.DataFrame:
    return data.loc[data['score']>=minimum_score]

In [73]:
select_high_scores(participants, 85)

      age group  score
id
1002   34     B     91
1003   29     A     85
1004   41     C     88
1006   37     A     95
1009   31     A     90

In [74]:
select_high_scores(participants, 90)

      age group  score
id
1002   34     B     91
1006   37     A     95
1009   31     A     90

Extension

Modify the function so the caller can also specify which columns to return.

In [75]:
def select_high_scores(
    data: pd.DataFrame,
    minimum_score: float,
    specific_columns: list
) -> pd.DataFrame:
    if specific_columns:
        return data.loc[data['score']>=minimum_score, specific_columns]
    
    return data.loc[data['score']>=minimum_score]

In [76]:
select_high_scores(participants, 90, 'age')

id
1002    34
1006    37
1009    31
Name: age, dtype: int64

### Part 24

In [77]:
good_data = participants.loc[
    participants["score"] > 80
]

In [78]:
MINIMUM_SCORE = 80

good_data = participants.loc[
    participants["score"] > MINIMUM_SCORE
]

Does naming the threshold improve reproducibility? What documentation is still missing?

Giving the threshold a name does improve reproducibility because it explicitly tells the user what the value represents. Some other good documentation would be naming the scores column as this may change from dataset to dataset.

### Part 25

Push to git

### Part 26

1. DataFrames

What does a pandas DataFrame provide that a list of dictionaries does not?

Improves subsetting, filtering, indexing, readability, etc.

2. What is the difference between:

df["age"]

and: 

df[["age"]] ?

df["age"] returns a pandas series, while df[["age"]] returns a dataframe.

3. .loc vs. .iloc

Explain the difference in one sentence.

.loc uses conditional indexing while .iloc uses positional indexing.

In [79]:
participants['score'] >= 85

id
1001    False
1002     True
1003     True
1004     True
1005    False
1006     True
1007    False
1008    False
1009     True
1010    False
Name: score, dtype: bool

4. Boolean filtering

What does:

df["score"] >= 85

produce before it is used to subset a DataFrame?

It returns a pandas series of booleans for all elements in the dataframe representing if the condition (score of at least 85) is True or False.

5. Analysis populations

Why is a pandas filter more than simply a programming operation?

Pandas filtering does not return a new object, it subsets the original while keeping the original intact.

6. Validation

Why should you inspect a filtered dataset even if no Python error occurred?

To ensure that the filter only includes the desired elements.

7. Reproducibility

How can explicit filtering criteria make statistical analyses easier to reproduce?

It is more reproducable when the criteria are written out it is more readable.